top: build

build:
	make -f fpellpts.mk
	make -f fpelladd.mk
	make -f ftellpts.mk
	make -f ftelladd.mk

mk:
	yamm fpellpts.mki
	yamm fpelladd.mki
	yamm ftellpts.mki
	yamm ftelladd.mki

clean:
	make -f fpellpts.mk clean
	make -f fpelladd.mk clean
	make -f ftellpts.mk clean
	make -f ftelladd.mk clean
